### ISSUE TITLE
SPARKNET distrbuted CPU with caffe.

### ISSUE THREAD

**Issue by mazene** [amplab/SparkNet#50]
Hi,
I am currently trying to use SparkNet with distributed CPU instead of GPU (for some comparisons), I have set Caffe with CPU_only config in caffe makefile configuration and then compiled SparkNet, then I submitted the CIFAR app locally : 
spark-submit --master local[*] --class apps.CifarApp SparkNet/target/scala-2.10/sparknet-assembly-0.1-SNAPSHOT.jar 1
I am getting the following : F0108 11:18:43.727069 13912 split_layer.cpp:53] Cannot use GPU in CPU-only Caffe: check mode.

What other modifications need to be done so that SparkNet perform the training on distrbuted CPU smoothly.

what happens to the executor JVM thread (that originally owns the RDD partition data ) when control is given to the GPU for processing? what if another thread is scheduled on that executor while a previous thread is doing computations on the GPU?

how does your design integrate with SPARK original spark DAG and task scheduler? is the cluster manager aware of the existence of GPU and make scheduling decisions accordingly? what if the cluster manager schedule the task (JVM thread on a non-GPU enabled nodes)?

Thank you.

**Comment by mazene** [comment]
modifying the  caffeLib.set_mode_gpu() to caffeLib.set_mode_cpu() will do the job , for distrbuted CPU training
could you please hint me about my other questions?
Many thanks.

**Comment by robertnishihara** [comment]
Yes, making that change should be enough! To answer some of your questions, Spark doesn't know about the GPU resources (so we can't always expect the scheduler to do reasonable things). This actually can pose a bit of a problem, because we need to ensure that some of our RDDs have exactly one partition per node (e.g., we want one deep net per node). If you simply do something like `val workers = sc.parallelize(Array.range(0, numWorkers), numWorkers)`, to create an RDD with `numWorkers` partitions, you are not guaranteed to have one partition per node. One way to solve this is to pass `--executor-cores 1` into the `spark-submit` script. That will ensure that the RDD has one partition per node.

Does that answer your question?

**Comment by mazene** [comment]
Great, so the design handle one executor (worker) per machine with only one RDD partition per machine. 
Thank you for open sourcing the code, very beneficial.

**Comment by robertnishihara** [comment]
Thanks!
