### ISSUE TITLE
would you please have cmake ../libccaffe support USE_CUDNN

### ISSUE THREAD

**Issue by nhe150** [amplab/SparkNet#82]
without cudnn, the performance degrade 6-10 times.

**Comment by robertnishihara** [comment]
Hi Norman, thanks for bringing this up, this is a very important point! CUDNN makes a huge difference in training time. We recently removed `libccaffe` from the codebase and replaced it with JavaCPP (see #72). This makes deployment a lot easier, so the user doesn't have to build `libccaffe`. The downside is that we currently haven't enabled GPUs with JavaCPP because of a bug bytedeco/javacpp-presets#147. We're working on figuring this out. Once that's done we will support CUDNN!

**Comment by nhe150** [comment]
Thank you. Working with bytedeco/javacpp seems to be very good approach.
